### ISSUE TITLE
unable to install docker

### ISSUE THREAD

**Issue by dibbinz** [dibbinz/Kali-Rehydrate#17]
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
sudo chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
sudo apt-get update

**Comment by ITmustang** [comment]
curl -fsSL https://download.docker.com/linux/debian/gpg

needs to be debian not ubuntu
