### ISSUE TITLE
add nessus

### ISSUE THREAD

**Issue by ITmustang** [dibbinz/Kali-Rehydrate#9]
cd /opt/ &&
curl --request GET \
  --url 'https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.7.4-ubuntu1404_amd64.deb' \
  --output 'Nessus-10.7.4-ubuntu1404_amd64.deb'
&& dpkg -i Nessus-10.7.4-ubuntu1404_amd64.deb

**Comment by dibbinz** [comment]
Nessus now added to script.
